swagger: "2.0"
info:
  title: "HDS coin server"
  description: "HDS coin server - the best cryptocurrency ever"
  version: "1.0-SNAPSHOT"
host: "localhost:8080"
schemes:
- "http"

paths:
  /register:
    post:
      operationId: "register"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/RegisterRequest"


definitions:
  PublicKey:
    type: object
    properties:
      value:
        type: string

  RegisterRequest:
    type: object
    properties:
      publicKey:
        $ref: "#/definitions/PublicKey"