swagger: "2.0"
info:
  title: "HDS coin server"
  description: "HDS coin server - the best cryptocurrency ever"
  version: "1.0-SNAPSHOT"
host: "localhost:8080"
schemes:
- "http"

paths:
  /register:
    post:
      operationId: "register"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/RegisterRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/RegisterResponse"
        400:
          description: "Invalid Key"

  /sendAmount:
    post:
      operationId: "send_amount"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SendAmountRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SendAmountResponse"
        400:
          description: "Invalid Key"

  /checkAccount:
    post:
      operationId: "check_account"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#definitions/CheckAccountRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/CheckAccountResponse"
        400:
          description: "Invalid Key"

  /receiveAmount:
    put:
      operationId: "receive_amount"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/ReceiveAmountRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ReceiveAmountResponse"
        400:
          description: "Invalid Key"

  /audit:
    post:
      operationId: "audit"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/AuditRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/AuditResponse"
        400:
          description: "Invalid Key"

definitions:
  PubKey:
    type: object
    properties:
      value:
        type: string

  Signature:
    type: object
    properties:
      value:
        type: string

  Hash:
    type: object
    properties:
      value:
        type: string

  TransactionInformation:
    type: object
    properties:
      transID:
        type: integer
      sourceKey:
        type: string
      destKey:
        type: string
      amount:
        type: string
      pending:
        type: boolean
      receive:
        type: boolean
      signature:
        $ref: "#/definitions/Signature"
      hash:
        $ref: "#/definitions/Hash"

  RegisterRequest:
    type: object
    properties:
      publicKey:
        $ref: "#/definitions/PubKey"
      signature:
        $ref: "#/definitions/Signature"

  RegisterResponse:
    type: object
    properties:
      message:
        type: string
      signature:
        $ref: "#/definitions/Signature"

  CheckAccountResponse:
      type: object
      properties:
        amount:
          type: string
        List:
          type: array
          items:
            $ref: "#/definitions/TransactionInformation"
        signature:
          $ref: "#/definitions/Signature"

  SendAmountRequest:
    type: object
    properties:
      sourceKey:
        $ref: "#/definitions/PubKey"
      destKey:
        $ref: "#/definitions/PubKey"
      amount:
        type: integer
      lastHash:
        $ref: "#/definitions/Hash"
      Signature:
        $ref: "#/definitions/Signature"

  SendAmountResponse:
    type: object
    properties:
      message:
        type: string
      newHash:
        $ref: "#/definitions/Hash"
      Signature:
        $ref: "#/definitions/Signature"

  CheckAccountRequest:
    type: object
    properties:
      publicKey:
        $ref: "#/definitions/PubKey"

  ReceiveAmountRequest:
    type: object
    properties:
      publicKey:
        $ref: "#/definitions/PubKey"
      transHash:
        $ref: "#/definitions/Hash"
      lastHash:
        $ref: "#/definitions/Hash"
      Signature:
        $ref: "#/definitions/Signature"

  ReceiveAmountResponse:
    type: object
    properties:
      message:
        type: string
      newHash:
        $ref: "#/definitions/Hash"
      Signature:
        $ref: "#/definitions/Signature"

  AuditRequest:
      type: object
      properties:
        publicKey:
          $ref: "#/definitions/PubKey"

  AuditResponse:
    type: object
    properties:
      List:
        type: array
        items:
          $ref: "#/definitions/TransactionInformation"
      Signature:
        $ref: "#/definitions/Signature"