swagger: "2.0"
info:
  title: "HDS coin server"
  description: "HDS coin server - the best cryptocurrency ever"
  version: "1.0-SNAPSHOT"
host: "localhost:8080"
schemes:
- "http"

paths:
  /register:
    post:
      operationId: "register"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/RegisterRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/RegisterResponse"
        400:
          description: "Invalid Key"

  /sendAmount:
    post:
      operationId: "send_amount"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SendAmountRequest"

  /checkAmount:
    post:
      operationId: "check_amount"
      parameters:
      - in: "body"
        name: "amount"
        required: true
        schema:
          $ref: "#definitions/CheckAmountRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            type: integer
        400:
          description: "Invalid Key"

definitions:
  PubKey:
    type: object
    properties:
      value:
        type: string

  RegisterRequest:
    type: object
    properties:
      publicKey:
        $ref: "#/definitions/PubKey"
  RegisterResponse:
    type: object
    properties:
      bla:
        type: array
        items:
          type: string

  SendAmountRequest:
    type: object
    properties:
      sourceKey:
        $ref: "#/definitions/PubKey"
      destKey:
        $ref: "#/definitions/PubKey"
      amount:
        type: integer

  CheckAmountRequest:
    type: object
    properties:
      publicKey:
        $ref: "#/definitions/PubKey"