swagger: "2.0"
info:
  title: "HDS coin server"
  description: "HDS coin server - the best cryptocurrency ever"
  version: "1.0-SNAPSHOT"
host: "localhost:8080"
schemes:
- "http"

paths:
  /register:
    post:
      operationId: "register"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/RegisterRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/RegisterResponse"
        400:
          description: "Invalid Key"

  /sendAmount:
    post:
      operationId: "send_amount"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SendAmountRequest"

  /checkAmount:
    get:
      operationId: "check_amount"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#definitions/CheckAmountRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/CheckAmountResponse"
        400:
          description: "Invalid Key"

  /receiveAmount:
    put:
      operationId: "receive_amount"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/ReceiveAmountRequest"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid Key"

  /audit:
    get:
      operationId: "audit"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/AuditRequest"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid Key"

definitions:
  PubKey:
    type: object
    properties:
      value:
        type: string

  Signature:
      type: object
      properties:
        value:
          type: string

  RegisterRequest:
    type: object
    properties:
      publicKey:
        $ref: "#/definitions/PubKey"
      signature:
        $ref: "#/definitions/Signature"

  RegisterResponse:
    type: object
    properties:
      message:
        type: array
        items:
          type: string

  CheckAmountResponse:
      type: object
      properties:
        message:
          type: array
          items:
            type: string

  SendAmountRequest:
    type: object
    properties:
      sourceKey:
        $ref: "#/definitions/PubKey"
      destKey:
        $ref: "#/definitions/PubKey"
      amount:
        type: integer
      Signature:
        $ref: "#/definitions/Signature"

  CheckAmountRequest:
    type: object
    properties:
      publicKey:
        $ref: "#/definitions/PubKey"

  ReceiveAmountRequest:
    type: object
    properties:
      publicKey:
        $ref: "#/definitions/PubKey"
      Signature:
        $ref: "#/definitions/Signature"

  AuditRequest:
      type: object
      properties:
        publicKey:
          $ref: "#/definitions/PubKey"